{{- if .Values.opensearch }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.opensearch.secretName }}
  labels:
    {{- include "demo-app-nextjs.labels" . | nindent 4 }}
type: Opaque
data:
  url: {{ .Values.opensearch.url | b64enc | quote }}
  username: {{ .Values.opensearch.username | b64enc | quote }}
  password: {{ .Values.opensearch.password | b64enc | quote }}
{{- end }}
