apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.elasticsearch.secretName }}
  labels:
    {{- include "demo-app-nextjs.labels" . | nindent 4 }}
type: Opaque
data:
  url: {{ .Values.elasticsearch.url | b64enc | quote }}
  username: {{ .Values.elasticsearch.username | b64enc | quote }}
  password: {{ .Values.elasticsearch.password | b64enc | quote }}
