apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo-app-nextjs.fullname" . }}
  labels:
    {{- include "demo-app-nextjs.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "demo-app-nextjs.selectorLabels" . | nindent 4 }}
---
{{- if .Values.externalAccess.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo-app-nextjs.fullname" . }}-external
  labels:
    {{- include "demo-app-nextjs.labels" . | nindent 4 }}
    app.kubernetes.io/component: external-access
  {{- with .Values.externalAccess.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.externalAccess.type }}
  ports:
    - port: {{ .Values.externalAccess.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "demo-app-nextjs.selectorLabels" . | nindent 4 }}
{{- end }}
