# Default values for demo-app-locust
image:
  repository: 211125671185.dkr.ecr.us-east-2.amazonaws.com/demo-locust
  pullPolicy: Always
  tag: "latest"

service:
  type: LoadBalancer
  port: 8089
  targetPort: 8089

resources:
  limits:
    cpu: "2"
    memory: "4Gi"
  requests:
    cpu: "2"
    memory: "4Gi"

config:
  targetHost: "http://demo-nextjs-demo-app-nextjs.demo-app.svc.cluster.local"
  
  # Load test parameters
  users: 50
  spawnRate: 50
  runTime: "500m"
  
  # Enable headless mode (no web UI, just run the test)
  headless: false

nodeSelector: {}
tolerations: []
affinity: {}
