apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "demo-app-locust.fullname" . }}
  labels:
    {{- include "demo-app-locust.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      {{- include "demo-app-locust.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "demo-app-locust.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: locust
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: web
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
            - name: LOCUST_MODE
              value: standalone
            - name: LOCUST_HOST
              value: {{ .Values.config.targetHost | quote }}
            - name: LOCUST_USERS
              value: {{ .Values.config.users | quote }}
            - name: LOCUST_SPAWN_RATE
              value: {{ .Values.config.spawnRate | quote }}
            - name: LOCUST_RUN_TIME
              value: {{ .Values.config.runTime | quote }}
            {{- if .Values.config.headless }}
            - name: LOCUST_HEADLESS
              value: "true"
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
